version: "3.8"
services:
  market: 
    build:
      context: .
      target: market
    ports:
      - "80:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: market_app
      POSTGRES_DB: market_db
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - progresDB:/var/lib/postgresql  # Use the named volume here
    ports:
      - "5432:5432"

volumes:
  progresDB:
