version: "3.8"
services:
  market: 
    build:
      context: .
      target: market
    env_file:
        - ./.env
    ports:
      - "8888:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:15.2
    env_file:
        - ./.env
    volumes:
      - "./postgres-data/pgdb:/var/lib/postgresql"
    ports:
      - "5432:5432"

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
volumes:
  progresDB:
