version: "3.8"
services:
  market: 
    build:
      context: .
      target: market
    ports:
      - "8888:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    environment:
      ./market/.env
    volumes:
      - progresDB:/var/lib/postgresql  # Use the named volume here
    ports:
      - "5432:5432"

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      ./market/.env
    ports:
      - "5050:8"

volumes:
  progresDB:
