[package]
name = "market"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.0"
axum = { version = "0.6.12", features = ["tracing"] }
axum-extra = { version = "0.7.2", features = ["cookie"] }
chrono = { version = "0.4.24", features = ["serde"] }
dotenv = "0.15"
jsonwebtoken = "8.3.0"
rand_core = { version = "0.6.4", features = ["std"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
sqlx = { version = "0.7", features = ["chrono", "rust_decimal", "json", "migrate", "postgres", "runtime-tokio-rustls", "uuid", "time"] }
thiserror = "1"
time = "0.3.20"
tokio = { version = "1.27.0", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.4.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
uuid = { version = "1.3.0", features = ["serde", "v4"] }
hyper = "0.14"
tower-layer = "0.3.2"
